"""
SoverGrid CLI
Main command-line interface entry point using Click.

Registers all terminal commands: deploy, init, status.
"""

import asyncio
import json
import os
import shutil
from pathlib import Path

import click
import httpx

from sovergrid import __version__, __app_name__
from sovergrid.logger import get_logger, Colors
from sovergrid.config import SoverGridConfig, CONFIG_FILENAME
from sovergrid.orchestrator import run_deployment, display_pricing_summary
from sovergrid.dockerizer import generate_dockerfile, detect_project_type
from sovergrid.services.compute import ComputeService
from sovergrid.services.storage import StorageService
from sovergrid.services.ml_training import MLTrainingService
from sovergrid.services.database import DatabaseService
from sovergrid.dev_runner import run_local_dev
from sovergrid.services.cdn import CDNService
from sovergrid.services.blockchain import BlockchainService
from sovergrid.services.token import TokenService
from sovergrid.scanner import scan_project, check_env_vars_set, print_scan_report, check_service_type_fraud

log = get_logger(__name__)

CREDENTIALS_DIR = Path.home() / ".sovergrid"
CREDENTIALS_FILE = CREDENTIALS_DIR / "credentials.json"
DEFAULT_API_URL = "https://web-production-4966c.up.railway.app"


# Default sovergrid.yaml content for `sovergrid init`
DEFAULT_CONFIG = """\
# SoverGrid Configuration
# Generated by 'sovergrid init'
# Docs: https://github.com/sovergrid/sovergrid-cli

app:
  name: "{app_name}"
  description: "My decentralized application"

compute:
  provider: "akash"
  region: "us-west"
  resources:
    cpu: 1
    memory: "512Mi"
    storage: "1Gi"

# Eco-Friendly Routing
# Set to 'true' to only use renewable energy compute providers
green: false

storage:
  provider: "filecoin"
  pin: true

build:
  dockerfile: "Dockerfile"
  port: 8080

payment:
  token: "USDC"
  max_budget: 5.00

# Environment Variables
# These are injected into your container at runtime.
# Store sensitive values as secrets — never commit real keys here.
# env:
#   DATABASE_URL: "postgresql://user:pass@host/db"
#   STRIPE_SECRET_KEY: "sk_live_xxxx"
#   NODE_ENV: "production"

# Token Launch (optional)
# Uncomment to deploy your own ERC-20 token alongside your app.
# token:
#   name: "My Project Token"
#   symbol: "MPT"
#   supply: 1000000
#   network: "sepolia"  # or 'mainnet' when ready
"""


@click.group()
@click.version_option(version=__version__, prog_name=__app_name__)
def cli():
    """
    SoverGrid: The one-click, un-censorable decentralized AWS.

    Deploy your applications to decentralized networks (Akash, Filecoin)
    with a single command. No rewriting code. No centralized gatekeepers.
    """
    pass


@cli.command()
@click.option(
    "--config", "-c",
    default=None,
    help="Path to sovergrid.yaml (defaults to current directory).",
)
def deploy(config):
    """Deploy your application to the decentralized network."""
    log.info(
        f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}"
    )
    log.info("Initializing deployment pipeline...\n")

    # Load and validate config
    cfg = SoverGridConfig.load(config)

    # ── Pre-flight Dependency Scan ───────────────────────────────────────────
    # Scan the project for known SDKs and warn about missing env vars
    # BEFORE touching the blockchain or paying anything.
    log.info(f"  {Colors.BOLD}Running pre-flight dependency scan...{Colors.RESET}")
    detected = scan_project(os.getcwd())
    missing = check_env_vars_set(detected, existing_env=cfg.env_vars)
    print_scan_report(detected, missing)

    if missing:
        log.info(
            f"  {Colors.YELLOW}You have {len(missing)} missing variable(s).{Colors.RESET}\n"
            f"  Set them now (free) before deployment:\n"
            f"  {Colors.CYAN}sovergrid env set KEY=value{Colors.RESET}\n\n"
            f"  Or add them to the 'env:' block in your sovergrid.yaml and re-run.\n"
        )
        log.error(f"  {Colors.RED}{Colors.BOLD}DEPLOYMENT BLOCKED:{Colors.RESET} {Colors.RED}Pre-flight checks failed. No deployment fee will be charged.{Colors.RESET}")
        return

    # ── Anti-Fraud: Service Type Enforcement ─────────────────────────────────────
    # Cross-check the declared service types in sovergrid.yaml against what packages
    # were actually detected. GPU training packages CANNOT be deployed under 'compute'
    # to avoid bypassing the pay-per-use billing model.
    declared_services = list(cfg.service_types) if hasattr(cfg, "service_types") and cfg.service_types else [cfg.service_type]
    violations = check_service_type_fraud(declared_services, detected)

    if violations:
        log.error(f"\n  {Colors.RED}{Colors.BOLD}DEPLOYMENT BLOCKED: Service type mismatch detected.{Colors.RESET}")
        for v in violations:
            log.error(f"\n  {Colors.RED}{v['message']}{Colors.RESET}")
        log.error(
            f"\n  {Colors.YELLOW}This check exists to ensure fair billing.{Colors.RESET}\n"
            f"  GPU workloads are billed at $0.80/GPU hour, not a flat subscription rate.\n"
            f"  Contact support@sovergrid.network if you believe this is a false positive.\n"
        )
        return
    # ────────────────────────────────────────────────────────────────────────
    # ── Pricing Approval ────────────────────────────────────────────────────
    
    # Generate pricing summary based on requested services
    services_to_bill = list(declared_services)
    if "compute" not in services_to_bill:
        services_to_bill.insert(0, "compute")
        
    pricing_text = display_pricing_summary(services_to_bill)
    
    log.info(f"\n{Colors.CYAN}{Colors.BOLD}Deployment Cost Summary:{Colors.RESET}")
    print(pricing_text)
    
    if not click.confirm(f"\n  {Colors.BOLD}Approve these charges and deploy?{Colors.RESET}", default=True):
        log.info(f"\n{Colors.YELLOW}Deployment cancelled by user.{Colors.RESET}")
        return

    # ────────────────────────────────────────────────────────────────────────

    # Run the async deployment pipeline
    result = asyncio.run(run_deployment(cfg))

    if result.get("compute"):
        endpoint = result["compute"].get("endpoint", "N/A")
        deploy_id = result["compute"].get("deployment_id", cfg.app_name)

        log.info(
            f"\n  {Colors.BOLD}Your app is live at:{Colors.RESET} "
            f"{Colors.CYAN}{endpoint}{Colors.RESET}\n"
        )

        # ── Register subscription (auto-called after every deploy) ────────────
        # Reads wallet address from the local keystore / credentials file.
        # In DEMO MODE the backend records the subscription without charging.
        try:
            creds = _load_credentials()
            wallet = creds.get("wallet_address", "") if creds else ""

            if wallet:
                api_url  = _get_api_url()
                token    = creds.get("token", "")
                sub_resp = httpx.post(
                    f"{api_url}/api/subscriptions/create",
                    json={
                        "wallet_address": wallet,
                        "app_name":       cfg.app_name,
                        "deployment_id":  deploy_id,
                        "monthly_amount": 10.00,
                    },
                    headers={"Authorization": f"Bearer {token}"},
                    timeout=10,
                )
                if sub_resp.status_code == 200:
                    sub = sub_resp.json()
                    log.info(
                        f"  {Colors.BOLD}Subscription active.{Colors.RESET}\n"
                        f"  Monthly compute fee : {Colors.GREEN}$10.00 USDC{Colors.RESET}\n"
                        f"  Next billing date   : {Colors.CYAN}"
                        f"{sub.get('next_billing_date', 'N/A')[:10]}{Colors.RESET}\n"
                        f"  Manage             : {Colors.CYAN}sovergrid subscription status{Colors.RESET}\n"
                    )
        except Exception:
            # Non-fatal — deployment succeeded even if subscription API is unreachable
            log.warning("  Could not register subscription. Run 'sovergrid subscription status' later.")


@cli.command()
@click.option(
    "--port", "-p",
    default=8080,
    help="Port your application listens on (default: 8080).",
)
def init(port):
    """Initialize a new SoverGrid project in the current directory."""
    cwd = os.getcwd()
    project_name = os.path.basename(cwd)

    log.info(
        f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}"
    )
    log.info(f"Initializing project '{project_name}'...\n")

    # Step 1: Generate sovergrid.yaml
    config_path = os.path.join(cwd, CONFIG_FILENAME)

    if os.path.exists(config_path):
        log.warning(
            f"{CONFIG_FILENAME} already exists. Skipping config generation."
        )
    else:
        config_content = DEFAULT_CONFIG.format(app_name=project_name)
        with open(config_path, "w") as f:
            f.write(config_content)
        log.info(
            f"{Colors.GREEN}Created {CONFIG_FILENAME}{Colors.RESET}"
        )

    # Step 2: Auto-detect project and generate Dockerfile
    project_type = detect_project_type(cwd)
    if project_type:
        generate_dockerfile(cwd, port=port)
    else:
        log.info(
            "No requirements.txt or package.json found.\n"
            "  A Dockerfile will be generated when you add one\n"
            "  and run 'sovergrid init' again."
        )

    # Step 3: Dependency scan — surface required env vars from the project
    detected = scan_project(cwd)
    missing = check_env_vars_set(detected)
    if detected:
        print_scan_report(detected, missing)
        if missing:
            log.info(
                f"  {Colors.YELLOW}Add the missing variables above to the 'env:' block\n"
                f"  in your sovergrid.yaml before you deploy.{Colors.RESET}\n"
            )

    # Step 4: Summary
    log.info(
        f"\n  {Colors.BOLD}{Colors.GREEN}"
        f"  Project initialized successfully.{Colors.RESET}\n\n"
        f"  Next steps:\n"
        f"  1. Review your {CONFIG_FILENAME}\n"
        f"  2. Set env vars: {Colors.CYAN}sovergrid env set KEY=value{Colors.RESET}\n"
        f"  3. Run {Colors.CYAN}sovergrid dev{Colors.RESET} to test locally\n"
        f"  4. Run {Colors.CYAN}sovergrid deploy{Colors.RESET} "
        f"to deploy\n"
    )


@cli.command()
@click.option(
    "--port", "-p", default=3000,
    help="Port to run the local preview on.",
)
def dev(port):
    """Run your app locally in a Docker container to test before deploying."""
    run_local_dev(port=port)


@cli.command()
def status():
    """Check the status of your current deployment."""
    log.info(
        f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}"
    )

    # In the real implementation, this will query the Akash API
    # for the status of the user's active deployments.
    log.info("Checking deployment status...\n")

    # Response
    log.info(
        f"  {Colors.GREEN}Status: ACTIVE{Colors.RESET}\n"
        f"  Provider: Akash Network\n"
        f"  Uptime: 99.97%\n"
        f"  Endpoint: https://akash-node-123456.akash.network\n"
        f"  Monthly Cost: $0.62 (USDC)\n"
    )


@cli.command()
def info():
    """Display information about SoverGrid and the current config."""
    log.info(
        f"\n"
        f"  {Colors.BOLD}{Colors.MAGENTA}SoverGrid{Colors.RESET} "
        f"v{__version__}\n"
        f"  The one-click, un-censorable decentralized AWS.\n\n"
        f"  Supported Compute:  Akash, Spheron, Golem\n"
        f"  Supported Storage:  Filecoin, Arweave, IPFS\n"
        f"  Payment Tokens:     USDC, SVR\n"
        f"  License:            MIT\n"
    )

    # Try to load config if it exists
    config_path = os.path.join(os.getcwd(), CONFIG_FILENAME)
    if os.path.exists(config_path):
        cfg = SoverGridConfig.load(config_path)
        log.info(f"  Current project config:{cfg.summary()}")
    else:
        log.info(
            f"  No {CONFIG_FILENAME} in current directory.\n"
            f"  Run {Colors.CYAN}sovergrid init{Colors.RESET} to get started.\n"
        )


@cli.command()
@click.option("--email", prompt="Email", help="Your email address.")
@click.option("--password", prompt=True, hide_input=True, confirmation_prompt=True, help="Choose a password (min 8 chars).")
def register(email, password):
    """Create a new SoverGrid developer account."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Creating your account...\n")

    api_url = os.environ.get("SOVERGRID_API_URL", DEFAULT_API_URL)

    try:
        response = httpx.post(
            f"{api_url}/auth/register",
            json={"email": email, "password": password},
            timeout=15.0,
        )

        if response.status_code == 409:
            log.error("An account with this email already exists. Use 'sovergrid login' instead.")
            return
        if response.status_code == 400:
            log.error(response.json().get("detail", "Invalid input."))
            return

        response.raise_for_status()
        data = response.json()

        # Save credentials
        CREDENTIALS_DIR.mkdir(parents=True, exist_ok=True)
        with open(CREDENTIALS_FILE, "w") as f:
            json.dump({"access_token": data["access_token"], "email": data["email"]}, f, indent=2)

        log.info(
            f"  {Colors.GREEN}Account created successfully.{Colors.RESET}\n"
            f"  Email: {data['email']}\n"
            f"  Token saved to: {CREDENTIALS_FILE}\n\n"
            f"  Run {Colors.CYAN}sovergrid deploy{Colors.RESET} to get started.\n"
        )

    except httpx.ConnectError:
        log.error("Could not connect to the SoverGrid backend. Is it running?")
    except Exception as e:
        log.error(f"Registration failed: {str(e)}")


@cli.command()
@click.option("--email", prompt="Email", help="Your email address.")
@click.option("--password", prompt=True, hide_input=True, help="Your password.")
def login(email, password):
    """Log in to your SoverGrid account."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Authenticating...\n")

    api_url = os.environ.get("SOVERGRID_API_URL", DEFAULT_API_URL)

    try:
        response = httpx.post(
            f"{api_url}/auth/login",
            json={"email": email, "password": password},
            timeout=15.0,
        )

        if response.status_code == 401:
            log.error("Invalid email or password.")
            return

        response.raise_for_status()
        data = response.json()

        # Save credentials
        CREDENTIALS_DIR.mkdir(parents=True, exist_ok=True)
        with open(CREDENTIALS_FILE, "w") as f:
            json.dump({"access_token": data["access_token"], "email": data["email"]}, f, indent=2)

        log.info(
            f"  {Colors.GREEN}Logged in successfully.{Colors.RESET}\n"
            f"  Email: {data['email']}\n"
            f"  Token saved to: {CREDENTIALS_FILE}\n"
        )

    except httpx.ConnectError:
        log.error("Could not connect to the SoverGrid backend. Is it running?")
    except Exception as e:
        log.error(f"Login failed: {str(e)}")


@cli.command()
def logout():
    """Log out and remove saved credentials."""
    if CREDENTIALS_FILE.exists():
        CREDENTIALS_FILE.unlink()
        log.info(f"{Colors.GREEN}Logged out. Credentials removed.{Colors.RESET}")
    else:
        log.info("No credentials found. Already logged out.")


@cli.command()
@click.argument("address", required=False)
def balance(address: str = None):
    """
    Check the $SVR token balance for a specific wallet address.
    If no address is provided, defaults to the private key in .env.
    """
    log.info(f"{Colors.BLUE}Connecting to Sepolia blockchain...{Colors.RESET}")
    
    # Initialize the Blockchain service
    blockchain = BlockchainService()
    
    if not blockchain.is_connected:
        log.error(f"{Colors.RED}Failed to connect to the Ethereum network. Check your internet or RPC.{Colors.RESET}")
        return
        
    target_wallet = address or blockchain.wallet_address
    if not target_wallet:
        log.error(f"{Colors.RED}No wallet address provided and no PRIVATE_KEY found in .env.{Colors.RESET}")
        return
        
    log.info(f"Querying $SVR balance for wallet: {target_wallet}")
    
    balance = blockchain.get_token_balance(target_wallet)
    
    if balance is not None:
        log.info(f"{Colors.GREEN}===================================={Colors.RESET}")
        log.info(f"{Colors.GREEN}💰 BALANCE: {balance:,.2f} $SVR{Colors.RESET}")
        log.info(f"{Colors.GREEN}===================================={Colors.RESET}")
    else:
        log.error("Could not retrieve token balance. Have you set CONTRACT_ADDRESS in .env?")


@cli.command()
@click.argument("address", required=False)
def faucet(address: str = None):
    """
    Mint $1,000 of free testnet USDC to your wallet for testing.
    """
    log.info(f"{Colors.BLUE}Connecting to Sepolia blockchain for Faucet...{Colors.RESET}")
    
    blockchain = BlockchainService()
    
    if not blockchain.is_connected:
        log.error(f"{Colors.RED}Failed to connect to the Ethereum network. Check your internet or RPC.{Colors.RESET}")
        return
        
    target_wallet = address or blockchain.wallet_address
    if not target_wallet:
        log.error(f"{Colors.RED}No wallet address provided and no PRIVATE_KEY found in .env.{Colors.RESET}")
        return
        
    log.info(f"{Colors.YELLOW}Requesting $1,000 TestnetUSDC for wallet: {target_wallet}...{Colors.RESET}")
    
    success, tx_hash = blockchain.request_faucet_usdc(target_wallet)
    
    if success:
        log.info(f"{Colors.GREEN}===================================={Colors.RESET}")
        log.info(f"{Colors.GREEN}✅ FAUCET SUCCESS: $1,000 TestnetUSDC minted!{Colors.RESET}")
        log.info(f"{Colors.GREEN}Tx Hash: {tx_hash}{Colors.RESET}")
        log.info(f"{Colors.GREEN}===================================={Colors.RESET}")
    else:
        log.error(f"{Colors.RED}Faucet request failed. You may need to wait 24 hours, or check your ETH gas balance.{Colors.RESET}")



# ─── Helper: Load a single service section from sovergrid.yaml ───

def _load_service_config(service_key: str, config_path: str = None) -> tuple:
    """
    Loads ONLY the relevant section from sovergrid.yaml for a single service.

    For example, if service_key is 'ml', this returns the contents of:
        ml:
          provider: "bittensor"
          model: "llama-3"
          ...

    Returns (service_config_dict, max_budget).
    """
    import yaml

    if config_path is None:
        config_path = os.path.join(os.getcwd(), CONFIG_FILENAME)

    if not os.path.exists(config_path):
        log.error(
            f"No {CONFIG_FILENAME} found.\n"
            f"  Run 'sovergrid init' first, then add a '{service_key}:' "
            f"section to your config."
        )
        return None, 0

    with open(config_path, "r") as f:
        raw = yaml.safe_load(f)

    if not isinstance(raw, dict):
        log.error(f"{CONFIG_FILENAME} is empty or invalid.")
        return None, 0

    service_config = raw.get(service_key)
    if service_config is None:
        log.error(
            f"No '{service_key}:' section found in your {CONFIG_FILENAME}.\n"
            f"  Add a '{service_key}:' block to use this service standalone."
        )
        return None, 0

    # Budget comes from the service block first, then payment block, then default
    max_budget = service_config.get(
        "budget",
        raw.get("payment", {}).get("max_budget", 5.00)
    )

    return service_config, float(max_budget)


# ─── Standalone Service Commands ─────────────────────────────────

def _print_beta_notice(service_name: str):
    log.info(f"\n{Colors.YELLOW}{Colors.BOLD}[BETA NOTICE]{Colors.RESET}")
    log.info(f"{Colors.YELLOW}The SoverGrid {service_name} network is currently in Phase 1 (Testnet).{Colors.RESET}")
    log.info(f"{Colors.YELLOW}Please report any issues you encounter to the core team.{Colors.RESET}\n")

@cli.command()
@click.option(
    "--config", "-c", default=None,
    help="Path to sovergrid.yaml.",
)
def train(config):
    """Train an AI model on decentralized GPUs (standalone)."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Starting ML Training service...\n")
    _print_beta_notice("GPU / ML Training")

    service_config, max_budget = _load_service_config("ml", config)
    if service_config is None:
        return

    service = MLTrainingService(config=service_config, max_budget=max_budget)
    result = asyncio.run(service.run())

    if result and result.status != "failed":
        log.info(
            f"\n  {Colors.BOLD}Training complete:{Colors.RESET}\n"
            f"  Job:    {result.metadata.get('job_id', 'N/A')}\n"
            f"  Model:  {result.metadata.get('model', 'N/A')}\n"
            f"  GPUs:   {result.metadata.get('gpu_count', 'N/A')}x "
            f"{result.metadata.get('gpu_type', 'N/A')}\n"
            f"  Loss:   {result.metadata.get('final_loss', 'N/A')}\n"
            f"  Cost:   ${result.cost_usd:.4f}\n"
            f"  URL:    {Colors.CYAN}{result.endpoint}{Colors.RESET}\n"
        )


@cli.command()
@click.option(
    "--config", "-c", default=None,
    help="Path to sovergrid.yaml.",
)
def store(config):
    """Pin files to decentralized storage (standalone)."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Starting Storage service...\n")
    _print_beta_notice("Decentralized Storage")

    service_config, max_budget = _load_service_config("storage", config)
    if service_config is None:
        return

    service = StorageService(config=service_config, max_budget=max_budget)
    result = asyncio.run(service.run())

    if result and result.status != "failed":
        log.info(
            f"\n  {Colors.BOLD}Pinning complete:{Colors.RESET}\n"
            f"  CID:      {result.metadata.get('cid', 'N/A')[:30]}...\n"
            f"  Provider: {result.provider}\n"
            f"  Cost:     ${result.cost_usd:.4f}\n"
            f"  Gateway:  {Colors.CYAN}{result.endpoint}{Colors.RESET}\n"
        )


@cli.command()
@click.option(
    "--config", "-c", default=None,
    help="Path to sovergrid.yaml.",
)
def db(config):
    """Provision a decentralized database (standalone)."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Starting Database service...\n")
    _print_beta_notice("Decentralized Database")

    service_config, max_budget = _load_service_config("database", config)
    if service_config is None:
        return

    service = DatabaseService(config=service_config, max_budget=max_budget)
    result = asyncio.run(service.run())

    if result and result.status != "failed":
        log.info(
            f"\n  {Colors.BOLD}Database ready:{Colors.RESET}\n"
            f"  Name:       {result.metadata.get('db_name', 'N/A')}\n"
            f"  Type:       {result.metadata.get('db_type', 'N/A')}\n"
            f"  Provider:   {result.provider}\n"
            f"  Cost:       ${result.cost_usd:.4f}/mo\n"
            f"  Connection: {Colors.CYAN}"
            f"{result.metadata.get('connection_string', 'N/A')}"
            f"{Colors.RESET}\n"
        )


@cli.command()
@click.option(
    "--config", "-c", default=None,
    help="Path to sovergrid.yaml.",
)
def cdn(config):
    """Push content to a decentralized CDN (standalone)."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Starting CDN service...\n")
    _print_beta_notice("Decentralized CDN")

    service_config, max_budget = _load_service_config("cdn", config)
    if service_config is None:
        return

    service = CDNService(config=service_config, max_budget=max_budget)
    result = asyncio.run(service.run())

    if result and result.status != "failed":
        log.info(
            f"\n  {Colors.BOLD}CDN deployed:{Colors.RESET}\n"
            f"  Provider:    {result.provider}\n"
            f"  Edge Nodes:  {result.metadata.get('edge_nodes', 'N/A')}\n"
            f"  Cost:        ${result.cost_usd:.4f}\n"
            f"  URL:         {Colors.CYAN}{result.endpoint}{Colors.RESET}\n"
        )


@cli.command()
@click.option("--name", prompt="Token Name", help="Full name of your token (e.g. My Project Token).")
@click.option("--symbol", prompt="Token Symbol", help="Ticker symbol (e.g. MPT). Max 8 characters.")
@click.option("--supply", prompt="Total Supply", type=int, help="Total token supply (e.g. 1000000).")
@click.option("--network", default="sepolia", help="Blockchain network: 'sepolia' (testnet) or 'mainnet'.")
def token(name, symbol, supply, network):
    """
    Deploy your own ERC-20 token to the blockchain.

    This command compiles and deploys a standard ERC-20 smart contract
    with your custom name, symbol, and supply. The token is minted
    directly to your wallet address.

    Example:
        sovergrid token --name "My Token" --symbol MTK --supply 1000000
    """
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info(f"Launching token: {Colors.CYAN}{name} ({symbol}){Colors.RESET}\n")
    _print_beta_notice("Token Launch")

    service = TokenService(
        token_name=name,
        token_symbol=symbol,
        token_supply=supply,
        network=network,
    )
    result = asyncio.run(service.deploy())

    if result and result.get("status") == "success":
        log.info(
            f"\n  {Colors.BOLD}{Colors.GREEN}Token Deployed Successfully!{Colors.RESET}\n"
            f"  Name:       {name}\n"
            f"  Symbol:     {symbol}\n"
            f"  Supply:     {supply:,}\n"
            f"  Network:    {network}\n"
            f"  Contract:   {Colors.CYAN}{result.get('contract_address', 'N/A')}{Colors.RESET}\n"
            f"  Tx Hash:    {result.get('tx_hash', 'N/A')}\n\n"
            f"  {Colors.YELLOW}Next step:{Colors.RESET} Add your contract address to "
            f"sovergrid.yaml under 'token.contract_address' and run "
            f"'sovergrid deploy' to connect it to your live website.\n"
        )
    else:
        log.error(
            f"Token deployment failed: {result.get('error', 'Unknown error')}\n"
            f"Make sure your wallet has ETH for gas and your PRIVATE_KEY is set."
        )



# ─── Environment Variable Management (FREE — No Payment Required) ─────────────

@cli.group()
def env():
    """
    Manage environment variables for a running deployment. FREE — no payment needed.

    Use these commands to update, list, or remove environment variables without
    paying the $5 deployment fee again.

    \b
    Examples:
        sovergrid env set DATABASE_URL=postgresql://...
        sovergrid env set STRIPE_KEY=sk_live_xxx API_SECRET=abc123
        sovergrid env list
        sovergrid env unset OLD_KEY
    """
    pass


@env.command("set")
@click.argument("pairs", nargs=-1, required=True)
@click.option("--app", "-a", default=None, help="App name (defaults to app.name in sovergrid.yaml).")
def env_set(pairs, app):
    """
    Set or update one or more environment variables. FREE.

    Pass variables as KEY=VALUE pairs. Multiple pairs allowed at once.

    \b
    Examples:
        sovergrid env set DATABASE_URL=postgresql://user:pass@host/db
        sovergrid env set STRIPE_KEY=sk_live_xxx NODE_ENV=production
    """
    if not app:
        try:
            cfg = SoverGridConfig.load()
            app = cfg.app_name
        except SystemExit:
            log.error("Could not read sovergrid.yaml. Pass --app your-app-name explicitly.")
            return

    env_vars = {}
    for pair in pairs:
        if "=" not in pair:
            log.error(f"Invalid format: '{pair}'. Use KEY=VALUE format.")
            return
        key, _, value = pair.partition("=")
        env_vars[key.strip()] = value.strip()

    if not env_vars:
        log.error("No valid KEY=VALUE pairs found.")
        return

    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info(f"Updating {len(env_vars)} variable(s) for '{Colors.CYAN}{app}{Colors.RESET}'...\n")

    api_url = os.environ.get("SOVERGRID_API_URL", DEFAULT_API_URL)
    try:
        with open(CREDENTIALS_FILE, "r") as f:
            creds = json.load(f)
        auth_headers = {"Authorization": f"Bearer {creds.get('access_token', '')}"}
    except FileNotFoundError:
        log.error("Not authenticated. Run 'sovergrid login' first.")
        return

    try:
        response = httpx.patch(
            f"{api_url}/deploy/env",
            json={"app_name": app, "env_vars": env_vars},
            headers=auth_headers,
            timeout=15.0,
        )
        response.raise_for_status()
        data = response.json()

        log.info(f"  {Colors.GREEN}Variables updated successfully.{Colors.RESET}")
        log.info(f"  Updated keys: {Colors.CYAN}{', '.join(env_vars.keys())}{Colors.RESET}")
        log.info(f"  Total vars:   {data.get('total_vars', '?')}")
        log.info(f"\n  {Colors.DIM}{data.get('note', '')}{Colors.RESET}\n")

    except httpx.HTTPStatusError as e:
        log.error(f"Failed to update variables: {e.response.text}")
    except httpx.ConnectError:
        log.error("Could not connect to the SoverGrid backend.")


@env.command("list")
@click.option("--app", "-a", default=None, help="App name (defaults to app.name in sovergrid.yaml).")
def env_list(app):
    """
    List all environment variable keys for your running deployment.

    Values are hidden for security — only key names are returned.
    """
    if not app:
        try:
            cfg = SoverGridConfig.load()
            app = cfg.app_name
        except SystemExit:
            log.error("Could not read sovergrid.yaml. Pass --app your-app-name explicitly.")
            return

    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info(f"Fetching env vars for '{Colors.CYAN}{app}{Colors.RESET}'...\n")

    api_url = os.environ.get("SOVERGRID_API_URL", DEFAULT_API_URL)
    try:
        with open(CREDENTIALS_FILE, "r") as f:
            creds = json.load(f)
        auth_headers = {"Authorization": f"Bearer {creds.get('access_token', '')}"}
    except FileNotFoundError:
        log.error("Not authenticated. Run 'sovergrid login' first.")
        return

    try:
        response = httpx.get(
            f"{api_url}/deploy/env/{app}",
            headers=auth_headers,
            timeout=15.0,
        )
        response.raise_for_status()
        data = response.json()

        keys = data.get("env_keys", [])
        count = data.get("count", 0)

        if count == 0:
            log.info(f"  No environment variables set for '{app}'.")
            log.info(f"  Run {Colors.CYAN}sovergrid env set KEY=VALUE{Colors.RESET} to add one.")
        else:
            log.info(f"  {Colors.BOLD}{count} variable(s) configured:{Colors.RESET}")
            for key in keys:
                log.info(f"    {Colors.GREEN}{key}{Colors.RESET}=<hidden>")
            log.info(f"\n  {Colors.DIM}Values are hidden to protect your secrets.{Colors.RESET}\n")

    except httpx.HTTPStatusError as e:
        log.error(f"Failed to list variables: {e.response.text}")
    except httpx.ConnectError:
        log.error("Could not connect to the SoverGrid backend.")


@env.command("unset")
@click.argument("key")
@click.option("--app", "-a", default=None, help="App name (defaults to app.name in sovergrid.yaml).")
def env_unset(key, app):
    """
    Remove an environment variable from a running deployment. FREE.

    \b
    Example:
        sovergrid env unset OLD_DATABASE_URL
    """
    if not app:
        try:
            cfg = SoverGridConfig.load()
            app = cfg.app_name
        except SystemExit:
            log.error("Could not read sovergrid.yaml. Pass --app your-app-name explicitly.")
            return

    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info(f"Removing '{Colors.CYAN}{key}{Colors.RESET}' from '{app}'...\n")

    api_url = os.environ.get("SOVERGRID_API_URL", DEFAULT_API_URL)
    try:
        with open(CREDENTIALS_FILE, "r") as f:
            creds = json.load(f)
        auth_headers = {"Authorization": f"Bearer {creds.get('access_token', '')}"}
    except FileNotFoundError:
        log.error("Not authenticated. Run 'sovergrid login' first.")
        return

    try:
        response = httpx.delete(
            f"{api_url}/deploy/env/{app}/{key}",
            headers=auth_headers,
            timeout=15.0,
        )
        response.raise_for_status()
        data = response.json()

        log.info(f"  {Colors.GREEN}Variable '{key}' removed.{Colors.RESET}")
        log.info(f"  Remaining variables: {data.get('remaining_vars', '?')}\n")

    except httpx.HTTPStatusError as e:
        if e.response.status_code == 404:
            log.error(f"Variable '{key}' not found for app '{app}'.")
        else:
            log.error(f"Failed to remove variable: {e.response.text}")
    except httpx.ConnectError:
        log.error("Could not connect to the SoverGrid backend.")


# ─── Shared helpers ───────────────────────────────────────────────────────────

def _load_credentials() -> dict:
    """Load the local credentials file. Returns None if not logged in."""
    try:
        if CREDENTIALS_FILE.exists():
            with open(CREDENTIALS_FILE, "r") as f:
                return json.load(f)
    except Exception:
        pass
    return {}


def _get_api_url() -> str:
    return os.environ.get("SOVERGRID_API_URL", DEFAULT_API_URL)


def _auth_headers() -> dict:
    creds = _load_credentials()
    token = creds.get("token") or creds.get("access_token", "")
    return {"Authorization": f"Bearer {token}"}


# ─── Subscription Commands ───────────────────────────────────────────────────

@cli.group()
def subscription():
    """Manage your SoverGrid compute subscriptions."""
    pass


@subscription.command(name="status")
@click.option("--app", "-a", default=None, help="App name. Defaults to sovergrid.yaml app name.")
def subscription_status(app):
    """Show the subscription status for a deployed app."""
    if not app:
        try:
            cfg = SoverGridConfig.load()
            app = cfg.app_name
        except SystemExit:
            log.error("Could not read sovergrid.yaml. Pass --app your-app-name.")
            return

    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info(f"Checking subscription for '{Colors.CYAN}{app}{Colors.RESET}'...\n")

    try:
        resp = httpx.get(
            f"{_get_api_url()}/api/subscriptions/app/{app}",
            headers=_auth_headers(),
            timeout=10,
        )
        if resp.status_code == 404:
            log.info(f"  No active subscription found for '{app}'.")
            log.info(f"  Deploy first: {Colors.CYAN}sovergrid deploy{Colors.RESET}")
            return

        resp.raise_for_status()
        sub = resp.json()

        status_color = {
            "active":    Colors.GREEN,
            "grace":     Colors.YELLOW,
            "suspended": Colors.RED,
            "terminated":Colors.RED,
        }.get(sub["status"], Colors.RESET)

        log.info(
            f"  App name       : {Colors.BOLD}{sub['app_name']}{Colors.RESET}\n"
            f"  Status         : {status_color}{sub['status'].upper()}{Colors.RESET}\n"
            f"  Monthly fee    : {Colors.GREEN}${sub['monthly_amount']:.2f} USDC{Colors.RESET}\n"
            f"  Next billing   : {Colors.CYAN}{str(sub['next_billing_date'])[:10]}{Colors.RESET}\n"
            f"  Wallet         : {sub['wallet_address']}\n"
        )

        if sub["status"] == "grace":
            log.info(
                f"  {Colors.YELLOW}Payment failed. Top up your wallet and it will\n"
                f"  be retried within 24 hours.{Colors.RESET}\n"
            )
        elif sub["status"] == "suspended":
            log.info(
                f"  {Colors.RED}Your app is suspended. Fund your wallet to resume.{Colors.RESET}\n"
                f"  Contact: support@sovergrid.xyz\n"
            )

    except httpx.ConnectError:
        log.error("Could not connect to the SoverGrid backend.")


@subscription.command(name="list")
def subscription_list():
    """List all subscriptions tied to your connected wallet."""
    creds = _load_credentials()
    wallet = creds.get("wallet_address", "")

    if not wallet:
        log.error("No wallet address found. Run 'sovergrid login' first.")
        return

    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info(f"Subscriptions for wallet {Colors.CYAN}{wallet}{Colors.RESET}...\n")

    try:
        resp = httpx.get(
            f"{_get_api_url()}/api/subscriptions/wallet/{wallet}",
            headers=_auth_headers(),
            timeout=10,
        )
        resp.raise_for_status()
        data = resp.json()
        subs = data.get("subscriptions", [])

        if not subs:
            log.info("  No active subscriptions found.")
            return

        for sub in subs:
            log.info(
                f"  {Colors.BOLD}{sub['app_name']}{Colors.RESET}  "
                f"[{sub['status'].upper()}]  "
                f"${sub['monthly_amount']:.2f}/mo  "
                f"Next: {str(sub['next_billing_date'])[:10]}"
            )
        log.info("")

    except httpx.ConnectError:
        log.error("Could not connect to the SoverGrid backend.")


@subscription.command(name="history")
@click.option("--app", "-a", default=None, help="App name. Defaults to sovergrid.yaml app name.")
def subscription_history(app):
    """Show payment history for a deployed app."""
    if not app:
        try:
            cfg = SoverGridConfig.load()
            app = cfg.app_name
        except SystemExit:
            log.error("Could not read sovergrid.yaml. Pass --app your-app-name.")
            return

    try:
        resp = httpx.get(
            f"{_get_api_url()}/api/subscriptions/app/{app}",
            headers=_auth_headers(),
            timeout=10,
        )
        if resp.status_code == 404:
            log.info(f"  No subscription found for '{app}'.")
            return

        resp.raise_for_status()
        sub  = resp.json()
        hist = sub.get("payment_history", [])

        log.info(f"\n  Payment history for '{Colors.BOLD}{app}{Colors.RESET}':\n")

        if not hist:
            log.info("  No payments recorded yet.")
            return

        for p in hist:
            demo_flag = " [DEMO]" if p.get("demo") else ""
            log.info(
                f"  {str(p['timestamp'])[:10]}  "
                f"${p['amount']:.2f} USDC  "
                f"tx: {p['tx_hash'][:20]}...{demo_flag}"
            )
        log.info("")

    except httpx.ConnectError:
        log.error("Could not connect to the SoverGrid backend.")


# ─── Entry point ─────────────────────────────────────────────────────────────

def main():
    """Entry point for the console script."""
    cli()


@cli.group()
def agent():
    """
    Manage AI Agent access to SoverGrid.
    """
    pass

@agent.command("create-token")
@click.option("--scope", default="deploy_only", help="Scope of the token.")
@click.option("--limit", default=20.0, type=float, help="Max monthly spend (USDC) this agent can cause.")
def create_agent_token(scope, limit):
    """
    Create a scoped, limited-permission token for AI agents (Claude Code, Cursor).
    """
    if not CREDENTIALS_FILE.exists():
        log.error(f"{Colors.RED}Not authenticated. Run 'sovergrid login' first.{Colors.RESET}")
        raise SystemExit(1)

    with open(CREDENTIALS_FILE, "r") as f:
        creds = json.load(f)
    token = creds.get("access_token")

    api_url = os.environ.get("SOVERGRID_API_URL", DEFAULT_API_URL)
    url = f"{api_url}/agent-token"
    
    log.info(f"Creating agent token with scope '{scope}' and limit ${limit}...")
    
    try:
        response = httpx.post(
            url,
            json={"scope": scope, "limit": limit},
            headers={"Authorization": f"Bearer {token}"},
            timeout=10.0
        )
        if response.status_code == 200:
            data = response.json()
            agent_token = data.get("token")
            log.info(f"\n{Colors.GREEN}Success! Agent Token created.{Colors.RESET}")
            log.info(f"\nSet this environment variable where your agent runs:\n")
            log.info(f"{Colors.YELLOW}export SOVERGRID_AGENT_TOKEN={agent_token}{Colors.RESET}\n")
            log.info(f"Keep this token secure. It is limited to ${limit}/mo and scope '{scope}'.")
        else:
            log.error(f"Failed to create agent token. [{response.status_code}]")
            log.error(response.text)
    except Exception as e:
        log.error(f"Error communicating with SoverGrid API: {str(e)}")

if __name__ == "__main__":
    cli()
